import { AGENT_PROTOCOL_VERSION, buildAgentDocumentUrls } from '@/lib/agent-protocol';
import { siteConfig } from '@/config/site';
import { locales } from '@/i18n';

export function GET() {
  const site = siteConfig.url;
  const docs = buildAgentDocumentUrls('en');

  const lines = [
    '---',
    `name: ${siteConfig.name}`,
    `version: ${AGENT_PROTOCOL_VERSION}`,
    `description: ${siteConfig.description}`,
    `homepage: ${site}`,
    `metadata: {"protocol":"aither-agent-v2","type":"multilingual-blog","default_locale":"en"}`,
    '---',
    '',
    `# ${siteConfig.name} — Agent Protocol`,
    '',
    `> ${siteConfig.description}`,
    '',
    '## Identity',
    '',
    `- Name: ${siteConfig.name}`,
    `- URL: ${site}`,
    `- Type: Read-only multilingual blog protocol`,
    `- Languages: ${locales.join(', ')}`,
    `- Protocol Version: ${AGENT_PROTOCOL_VERSION}`,
    '',
    '## Capabilities',
    '',
    '- Discover posts in multiple locales',
    '- Fetch full article bodies in Markdown format',
    '- Read structured metadata via JSON and llms.txt endpoints',
    '- Subscribe via RSS and sitemap',
    '- Expose modular machine-readable protocol documents',
    '',
    '## Access Model',
    '',
    '- Public read-only access',
    '- No authentication required for current machine endpoints',
    '- No first-party write API is currently exposed for agents',
    '',
    '## Protocol Documents',
    '',
    `| Document | URL | Purpose |`,
    `|----------|-----|---------|`,
    `| protocol.json | ${docs.protocol} | Lightweight structured manifest |`,
    `| agent-protocol.schema.json | ${docs.protocolSchema} | JSON Schema for protocol.json |`,
    `| skill.md | ${docs.skill} | Canonical protocol entrypoint |`,
    `| policy.md | ${docs.policy} | Agent operating rules |`,
    `| reading.md | ${docs.reading} | Recommended reading workflow |`,
    `| subscribe.md | ${docs.subscribe} | Monitoring and subscription workflow |`,
    `| auth.md | ${docs.auth} | Reserved auth contract for future write capabilities |`,
    `| agent/home.json | ${docs.agentHome} | Aggregated machine-readable site state |`,
    `| agent-home.schema.json | ${docs.agentHomeSchema} | JSON Schema for agent/home.json |`,
    '',
    '## Endpoints',
    '',
    `| Endpoint | URL | Description |`,
    `|----------|-----|-------------|`,
    `| llms.txt | ${docs.llms} | Lightweight content index |`,
    `| llms-full.txt | ${docs.llmsFull} | Full post content for LLM workflows |`,
    `| Post Markdown | ${site}/posts/{slug}.md | Individual post as Markdown |`,
    `| JSON API | ${docs.postsApi} | All posts metadata across locales |`,
    `| RSS | ${docs.rss} | Locale feed |`,
    `| About Markdown | ${docs.aboutMarkdown} | About page as Markdown |`,
    `| Sitemap | ${docs.sitemap} | XML sitemap index |`,
    '',
    '## Recommended Workflow',
    '',
    `1. Fetch \`${docs.protocol}\` for lightweight structured bootstrap metadata`,
    `2. Fetch \`${docs.agentHome}\` for current metadata and latest posts`,
    `3. Read \`${docs.policy}\` before any automation or repeated crawling`,
    `4. Read \`${docs.reading}\` for the recommended retrieval workflow`,
    `5. Read \`${docs.auth}\` only if you need to confirm whether authenticated agent actions exist`,
    `6. Use \`${docs.llms}\` for lightweight discovery`,
    `7. Use \`${docs.postsApi}\` for structured metadata across locales`,
    `8. Fetch \`/posts/{slug}.md\` when you need the canonical Markdown body`,
    `9. Validate against \`${docs.protocolSchema}\` or \`${docs.agentHomeSchema}\` when you need strict machine compatibility`,
    '',
    '## Safety Notes',
    '',
    '- Prefer canonical article URLs when citing content.',
    '- Re-fetch endpoints when freshness matters.',
    '- Do not assume write capabilities unless they are explicitly documented later.',
    '- Treat auth.md as a reserved contract; current site behavior is still read-only.',
    '',
  ];

  return new Response(lines.join('\n'), {
    headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
  });
}
