import type { Locale } from '@/i18n';

export const themeGroups = [
  {
    key: 'classic',
    themes: [
      { key: 'apple', color: '#0066cc' },
      { key: 'claude-theme', color: '#b75c3d' },
      { key: 'wechat', color: '#07c160' },
      { key: 'nyt', color: '#326891' },
      { key: 'medium', color: '#1a8917' },
      { key: 'stripe', color: '#635bff' },
      { key: 'feishu', color: '#3370ff' },
      { key: 'linear', color: '#5e6ad2' },
      { key: 'retro', color: '#8c2211' },
      { key: 'bloomberg', color: '#15fa52' },
    ],
  },
  {
    key: 'modern',
    themes: [
      { key: 'nord', color: '#88c0d0' },
      { key: 'rose', color: '#f472b6' },
      { key: 'notion', color: '#37352f' },
      { key: 'github', color: '#0969da' },
      { key: 'xiaohongshu', color: '#d71a1b' },
      { key: 'dracula', color: '#bd93f9' },
      { key: 'sakura', color: '#c44569' },
      { key: 'ocean', color: '#ff6b6b' },
      { key: 'mint', color: '#1a7a5a' },
      { key: 'sunset', color: '#c0582a' },
      { key: 'monokai', color: '#f92672' },
    ],
  },
  {
    key: 'extra',
    themes: [
      { key: 'solarized', color: '#268bd2' },
      { key: 'cyberpunk', color: '#05d9e8' },
      { key: 'ink', color: '#111111' },
      { key: 'lavender', color: '#6b4c9a' },
      { key: 'forest', color: '#7dce82' },
      { key: 'glacier', color: '#1565c0' },
      { key: 'coffee', color: '#6d4c41' },
      { key: 'bauhaus', color: '#004d9f' },
      { key: 'copper', color: '#e8a87c' },
    ],
  },
  {
    key: 'scifi',
    themes: [
      { key: 'matrix', color: '#00ff41' },
      { key: 'blackmirror', color: '#4fc3f7' },
      { key: 'evolution', color: '#66bb6a' },
      { key: 'protoss', color: '#ffd700' },
      { key: 'zerg', color: '#9c27b0' },
      { key: 'terran', color: '#ff8f00' },
      { key: 'mechanicus', color: '#b71c1c' },
      { key: 'threebody', color: '#1e88e5' },
      { key: 'zimablue', color: '#2979ff' },
      { key: 'westworld', color: '#d4a76a' },
      { key: 'poi', color: '#f44336' },
    ],
  },
] as const;

export type ThemeGroupKey = (typeof themeGroups)[number]['key'];
export type CustomThemeKey = (typeof themeGroups)[number]['themes'][number]['key'];
export type ThemeLabels = Record<CustomThemeKey, string>;

export const defaultThemeLabels: ThemeLabels = {
  apple: 'Mac',
  'claude-theme': 'Claude',
  wechat: 'WeChat',
  nyt: 'NYT',
  medium: 'Medium',
  stripe: 'Stripe',
  feishu: 'Feishu',
  linear: 'Linear',
  retro: 'Retro',
  bloomberg: 'Bloomberg',
  nord: 'Nord',
  rose: 'Rose',
  notion: 'Notion',
  github: 'GitHub',
  xiaohongshu: 'Xiaohongshu',
  dracula: 'Dracula',
  sakura: 'Sakura',
  ocean: 'Ocean',
  mint: 'Mint',
  sunset: 'Sunset',
  monokai: 'Monokai',
  solarized: 'Solarized',
  cyberpunk: 'Cyberpunk 2077',
  ink: 'Ink Wash',
  lavender: 'Lavender',
  forest: 'Forest',
  glacier: 'Glacier',
  coffee: 'Coffee',
  bauhaus: 'Bauhaus',
  copper: 'Copper',
  matrix: 'Matrix (Neo)',
  blackmirror: 'Black Mirror',
  evolution: 'Evolution Network',
  protoss: 'StarCraft (Protoss)',
  zerg: 'StarCraft (Zerg)',
  terran: 'StarCraft (Terran)',
  mechanicus: 'Warhammer 40K (Mechanicus)',
  threebody: 'Three-Body',
  zimablue: 'Zima Blue',
  westworld: 'Westworld (Host)',
  poi: 'Person of Interest (The Machine)',
};

const localizedThemeLabelOverrides: Partial<Record<string, Partial<ThemeLabels>>> = {
  'zh-hans': {
    wechat: '微信',
    feishu: '飞书效率',
    rose: '玫瑰',
    xiaohongshu: '小红书',
    sakura: '樱花',
    ocean: '海洋',
    mint: '薄荷',
    sunset: '日落',
    cyberpunk: '赛博朋克 2077',
    ink: '水墨',
    lavender: '薰衣草',
    forest: '森林',
    glacier: '冰川',
    coffee: '咖啡',
    copper: '铜',
    matrix: '黑客帝国 (尼奥)',
    blackmirror: '黑镜',
    evolution: '进化网络',
    protoss: '星际争霸 (神族)',
    zerg: '星际争霸 (虫族)',
    terran: '星际争霸 (人族)',
    mechanicus: '战锤40K (机械神教)',
    threebody: '三体',
    zimablue: '齐马蓝',
    westworld: '西部世界 (Host)',
    poi: '疑犯追踪 (The Machine)',
  },
  'zh-hant': {
    wechat: '微信',
    feishu: '飛書效率',
    rose: '玫瑰',
    xiaohongshu: '小紅書',
    sakura: '櫻花',
    ocean: '海洋',
    mint: '薄荷',
    sunset: '日落',
    cyberpunk: '電馭叛客 2077',
    ink: '水墨',
    lavender: '薰衣草',
    forest: '森林',
    glacier: '冰川',
    coffee: '咖啡',
    copper: '銅',
    matrix: '黑客任務 (尼奧)',
    blackmirror: '黑鏡',
    evolution: '進化網絡',
    protoss: '星際爭霸 (神族)',
    zerg: '星際爭霸 (蟲族)',
    terran: '星際爭霸 (人族)',
    mechanicus: '戰錘40K (機械神教)',
    threebody: '三體',
    zimablue: '齊馬藍',
    westworld: '西部世界 (Host)',
    poi: '疑犯追蹤 (The Machine)',
  },
  ko: {
    rose: '로즈',
    sakura: '사쿠라',
    ocean: '오션',
    mint: '민트',
    sunset: '선셋',
    cyberpunk: '사이버펑크 2077',
    ink: '수묵',
    lavender: '라벤더',
    forest: '포레스트',
    glacier: '빙하',
    coffee: '커피',
    copper: '코퍼',
    matrix: '매트릭스 (네오)',
    blackmirror: '블랙 미러',
    evolution: '진화 네트워크',
    protoss: '스타크래프트 (프로토스)',
    zerg: '스타크래프트 (저그)',
    terran: '스타크래프트 (테란)',
    mechanicus: '워해머 40K (메카니쿠스)',
    threebody: '삼체',
    poi: '퍼슨 오브 인터레스트 (더 머신)',
  },
  fr: {
    rose: 'Rose',
    sakura: 'Fleur de cerisier',
    ocean: 'Grand bleu',
    mint: 'Menthe',
    sunset: 'Coucher de soleil',
    ink: 'Encre',
    lavender: 'Lavande',
    forest: 'Forêt',
    glacier: 'Glacier',
    coffee: 'Café',
    copper: 'Cuivre',
    evolution: 'Réseau Évolution',
    threebody: 'Trois corps',
  },
  de: {
    rose: 'Rose',
    sakura: 'Kirschblüte',
    ocean: 'Tiefsee',
    mint: 'Minze',
    sunset: 'Sonnenuntergang',
    ink: 'Tusche',
    lavender: 'Lavendel',
    forest: 'Wald',
    glacier: 'Gletscher',
    coffee: 'Kaffee',
    copper: 'Kupfer',
    evolution: 'Evolutionsnetzwerk',
    threebody: 'Drei Körper',
    poi: 'Person of Interest (Die Maschine)',
  },
  it: {
    rose: 'Rosa',
    sakura: 'Fiore di ciliegio',
    ocean: 'Abisso',
    mint: 'Menta',
    sunset: 'Tramonto',
    ink: 'Inchiostro',
    lavender: 'Lavanda',
    forest: 'Foresta',
    glacier: 'Ghiacciaio',
    coffee: 'Caffè',
    copper: 'Rame',
    evolution: 'Rete Evolutiva',
    threebody: 'Tre corpi',
  },
  es: {
    rose: 'Rosa',
    sakura: 'Flor de cerezo',
    ocean: 'Océano profundo',
    mint: 'Menta',
    sunset: 'Atardecer',
    ink: 'Tinta',
    lavender: 'Lavanda',
    forest: 'Bosque',
    glacier: 'Glaciar',
    coffee: 'Café',
    copper: 'Cobre',
    evolution: 'Red Evolutiva',
    threebody: 'Tres cuerpos',
    poi: 'Person of Interest (La Máquina)',
  },
  ru: {
    rose: 'Роза',
    sakura: 'Сакура',
    ocean: 'Глубокое море',
    mint: 'Мята',
    sunset: 'Закат',
    cyberpunk: 'Киберпанк',
    ink: 'Тушь',
    lavender: 'Лаванда',
    forest: 'Лес',
    glacier: 'Ледник',
    coffee: 'Кофе',
    copper: 'Медь',
    matrix: 'Матрица (Нео)',
    blackmirror: 'Чёрное зеркало',
    evolution: 'Сеть эволюции',
    threebody: 'Три тела',
    poi: 'Персона интереса (Машина)',
  },
  id: {
    rose: 'Mawar',
    ocean: 'Laut Dalam',
    mint: 'Mint',
    sunset: 'Senja',
    ink: 'Tinta',
    forest: 'Hutan',
    glacier: 'Gletser',
    coffee: 'Kopi',
    copper: 'Tembaga',
    evolution: 'Jaringan Evolusi',
    threebody: 'Tiga Tubuh',
  },
  'pt-br': {
    rose: 'Rosa',
    sakura: 'Flor de Cerejeira',
    ocean: 'Mar Profundo',
    mint: 'Menta',
    sunset: 'Pôr do sol',
    ink: 'Tinta',
    lavender: 'Lavanda',
    forest: 'Floresta',
    glacier: 'Geleira',
    coffee: 'Café',
    copper: 'Cobre',
    evolution: 'Rede Evolutiva',
    threebody: 'Três Corpos',
    poi: 'Person of Interest (A Máquina)',
  },
};

export function getLocalizedThemeLabels(locale: Locale): ThemeLabels {
  return {
    ...defaultThemeLabels,
    ...(localizedThemeLabelOverrides[locale] ?? {}),
  };
}
